apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc             # name of persistent volume claim
spec:
  storageClassName: nfs     # name of Storage Class Name, use same class name defined in PV
  accessModes:
    - ReadWriteMany         # specify same access mode defined in PV
  resources:
    requests:
      storage: 5Gi          # amount of storage requested
