---
# tasks file for deploy-traefik
- name: Add helm repo
  shell: /usr/local/bin/helm repo add traefik https://helm.traefik.io/traefik

- name: Update helm repos
  shell: /usr/local/bin/helm repo update

- name: Wait for kubernetes API to respond
  wait_for:
    port: 6443
    delay: 10

- name: Merge certs
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  loop:
    - cert.crt
    - key.pem

- name: Add certs to kubernetes cluster as a secret
  shell: /usr/local/bin/kubectl create secret tls custom-default-cert --cert cert.crt --key key.pem
  args:
    chdir: /tmp/

- name: Deploy traefik
  shell: /usr/local/bin/helm install traefik --set service.type=NodePort --set ports.web.nodePort=30001 --set ports.websecure.nodePort=30002 --set ports.websecure.tls.enabled=true --set deployment.replicas=3 traefik/traefik --version 9.19.2
  args:
    chdir: /tmp/

- name: Merge YAML
  template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  loop:
    - tlsstore.yml
    - app-deployment.yml
    - deployment2.yml
    - app-svc.yml
    - svc2.yml
    - app-ingress.yml
    - hello2-ingress.yml

- name: Apply YAML
  shell: /usr/local/bin/kubectl apply -f "{{ item }}"
  loop:
    - /tmp/tlsstore.yml
    - /tmp/app-deployment.yml
    - /tmp/deployment2.yml
    - /tmp/app-svc.yml
    - /tmp/svc2.yml
    - /tmp/app-ingress.yml
    - /tmp/hello2-ingress.yml
    
- name: Wait for http://app.lab.io to respond externally via ingress
  uri:
    url: "http://app.lab.io:30001"
    method: GET
    follow_redirects: none
  register: _result
  until: _result.status == 200
  retries: 30
  delay: 5

- name: Wait for https://hello2.lab.io to respond externally via ingress
  uri:
    url: "https://hello2.lab.io:30002"
    method: GET
    follow_redirects: none
    validate_certs: no
  register: _result
  until: _result.status == 200
  retries: 30
  delay: 5
