---
# tasks file for install-containerd

- name: Build containerd kernel module conf files
  template:
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf

- name: Load overlay kernel module
  modprobe:
    name: overlay 
    state: present

- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: Build containerd sysctl parameters
  template:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: Apply new sysctl parameters
  shell: sysctl --system
