---
# tasks file for change-password
- block:

  - name: Install AWS plugin collection via ansible-galaxy
    command: ansible-galaxy collection install amazon.aws

  - name: Install boto3 and botocore for root
    pip:
      name: [ "boto3", "botocore" ]

  - name: Install boto3 and botocore for non-privileged users
    pip:
      name: [ "boto3", "botocore" ]
      extra_args: "--user"

  when: install_plugin is defined


- name: Change root and mehlj password
  vars:
    credentials: "{{ lookup('amazon.aws.aws_secret', secret_name) }}"
  user:
    name: "{{ item }}"
    password: "{{ credentials.vsphere | password_hash('sha512') }}"
  loop:
    - mehlj
    - root
