---
# tasks file for change-password
- block:

  - name: Install AWS plugin collection via ansible-galaxy
    command: ansible-galaxy collection install amazon.aws

  - name: Install boto3 and botocore 
    pip:
      name: [ "boto3", "botocore" ]

  when: install_plugin is defined

- name: Check if boto3 is installed
  shell: pip3 list | grep boto3

- name: Sleep for 20 seconds and continue with play
  wait_for:
    timeout: 20
  delegate_to: localhost

- name: Change root and mehlj password
  vars:
    AWS_REGION: 'us-east-1'
    credentials: "{{ lookup('amazon.aws.aws_secret', 
                  secret_name,
                  region=AWS_REGION, 
                  aws_secret_key=(AWS_SECRET_ACCESS_KEY | string), 
                  aws_access_key=(AWS_ACCESS_KEY_ID | string)) }}"
  user:
    name: "{{ item }}"
    password: "{{ credentials.vsphere | password_hash('sha512') }}"
  loop:
    - mehlj
    - root
