---
# tasks file for change-password
- name: Install AWS plugin collection via ansible-galaxy
  command: ansible-galaxy collection install amazon.aws

- name: Install boto3 and botocore 
  pip:
    name: [ "boto3", "botocore" ]

- name: Check if boto3 is installed
  shell: pip3 list | grep boto3
 
- name: Find all python3 versions
  shell: find / -name python3
  
- name: Find all python versions
  shell: find / -name python
  
- name: Find default in-use python
  shell: which python
  
- name: find default in-use python3
  shell: which python3
  
- name: Find location of boto3
  shell: find / -name boto3

- name: Change root and mehlj password
  vars:
    AWS_REGION: 'us-east-1'
    credentials: "{{ lookup('amazon.aws.aws_secret', 
                  secret_name,
                  region=AWS_REGION, 
                  aws_secret_key=(AWS_SECRET_ACCESS_KEY | string), 
                  aws_access_key=(AWS_ACCESS_KEY_ID | string)) }}"
  user:
    name: "{{ item }}"
    password: "{{ credentials.vsphere | password_hash('sha512') }}"
  loop:
    - mehlj
    - root
